### ISSUE TITLE
The operator is not able to create a StorageClass

### ISSUE THREAD

**Issue by rvanbutselaar** [openshift/csi-driver-manila-operator#43]
Because the "csi-manila-default_share_type_cinder" name is an invalid name, see log below.

Our OpenStack provider only created a share type with the name: "default_share_type_cinder". We are not able to change the name or able to create new share types. So can we override the default `storageClassNamePrefix` using an environment variable or config file?

```
{"level":"info","ts":1595345817.1341367,"logger":"controller_maniladriver","msg":"Creating a new StorageClass","Request.Namespace":"","Request.Name":"cluster","StorageClass.Name":"csi-manila-default_share_type_cinder"}
{"level":"error","ts":1595345817.1385734,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"maniladriver-controller","request":"/cluster","error":"StorageClass.storage.k8s.io \"csi-manila-default_share_type_cinder\" is invalid: metadata.name: Invalid value: \"csi-manila-default_share_type_cinder\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/openshift/csi-driver-manila-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/openshift/csi-driver-manila-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/openshift/csi-driver-manila-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/src/github.com/openshift/csi-driver-manila-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/openshift/csi-driver-manila-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/openshift/csi-driver-manila-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/openshift/csi-driver-manila-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

**Comment by fmount** [comment]
[stack@standalone ocp]$ openstack share type list
    /usr/lib64/python3.6/site-packages/_yaml/__init__.py:23: DeprecationWarning: The _yaml extension module is now located at yaml._yaml and its location is subject to change.  To use the LibYAML-based parser and emitter, import from `yaml`: `from yaml import CLoader as Loader, CDumper as Dumper`.
      DeprecationWarning
    +--------------------------------------+------------------+------------+------------+--------------------------------------+-------------------------+-------------+
    | id                                   | name             | visibility | is_default | required_extra_specs                 | optional_extra_specs    | description |
    +--------------------------------------+------------------+------------+------------+--------------------------------------+-------------------------+-------------+
    | 1b3d4a3f-3c9e-47f5-949d-adac09fbf2bc | default          | public     | True       | driver_handles_share_servers : False | snapshot_support : True | None        |
    | f3e42448-31ff-4e5a-98e7-2bbf83e5a224 | tripleo_ceph_nfs | public     | False      | driver_handles_share_servers : False |                         | None        |
    +--------------------------------------+------------------+------------+------------+--------------------------------------+-------------------------+-------------+
     
     
     
    > oc get sc
    csi-manila-default   manila.csi.openstack.org   Delete          Immediate              false                  2m41s
    standard-csi         cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   76d
     
     
    I1124 19:53:39.381522 1011457 event.go:282] Event(v1.ObjectReference{Kind:"Namespace", Namespace:"manila-csi-driver", Name:"manila-csi-driver", UID:"", APIVersion:"v1", ResourceVersion:"",
    FieldPath:""}): type: 'Warning' reason: 'StorageClassCreateFailed' Failed to create StorageClass.storage.k8s.io/csi-manila-tripleo_ceph_nfs: StorageClass.storage.k8s.io "csi-manila-tripleo_
    ceph_nfs" is invalid: metadata.name: Invalid value: "csi-manila-tripleo_ceph_nfs": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must st
    art and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
    E1124 19:53:39.381726 1011457 base_controller.go:270] "ManilaController" controller failed to sync "key", err: StorageClass.storage.k8s.io "csi-manila-tripleo_ceph_nfs" is invalid: metadata
    .name: Invalid value: "csi-manila-tripleo_ceph_nfs": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumer
    ic character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
    I1124 19:53:39.381774 1011457 manila.go:87] Manila sync started
    I1124 19:53:39.381938 1011457 manila.go:98] I want to make a few checks before looking for the available share types
    I1124 19:53:39.451121 1011457 request.go:597] Waited for 192.412912ms due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/rbac.authoriza
    tion.k8s.io/v1/clusterrolebindings/manila-node-privileged-binding
    I1124 19:53:39.651443 1011457 request.go:597] Waited for 194.556742ms due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/rbac.authoriza
    tion.k8s.io/v1/clusterroles/manila-kube-rbac-proxy-role
    I1124 19:53:39.851703 1011457 request.go:597] Waited for 195.097321ms due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/rbac.authoriza
    tion.k8s.io/v1/clusterrolebindings/manila-kube-rbac-proxy-binding
    I1124 19:53:40.053105 1011457 request.go:597] Waited for 197.948828ms due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/rbac.authoriza
    tion.k8s.io/v1/namespaces/manila-csi-driver/roles/manila-csi-driver-prometheus
    I1124 19:53:40.251734 1011457 request.go:597] Waited for 190.038013ms due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/rbac.authoriza
    tion.k8s.io/v1/namespaces/manila-csi-driver/rolebindings/manila-csi-driver-prometheus
    E1124 19:53:40.255504 1011457 base_controller.go:270] "StaticResourceController" controller failed to sync "key", err: "volumesnapshotclass.yaml" (string): the server could not find the req
    uested resource
    I1124 19:53:40.276298 1011457 event.go:282] Event(v1.ObjectReference{Kind:"Namespace", Namespace:"manila-csi-driver", Name:"manila-csi-driver", UID:"", APIVersion:"v1", ResourceVersion:"",
    FieldPath:""}): type: 'Warning' reason: 'VolumeSnapshotClassCreateFailed' Failed to create VolumeSnapshotClass.snapshot.storage.k8s.io/v1: the server could not find the requested resource
    I1124 19:53:40.443622 1011457 manila.go:131] Syncing storage class for shareType type default
    I1124 19:53:40.451460 1011457 request.go:597] Waited for 174.972242ms due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/rbac.authoriza
    tion.k8s.io/v1/clusterrolebindings/manila-csi-snapshotter-binding
    I1124 19:53:40.458332 1011457 manila.go:131] Syncing storage class for shareType type tripleo_ceph_nfs
    I1124 19:53:40.483384 1011457 manila.go:122] Manila sync finished
    I1124 19:53:40.483555 1011457 event.go:282] Event(v1.ObjectReference{Kind:"Namespace", Namespace:"manila-csi-driver", Name:"manila-csi-driver", UID:"", APIVersion:"v1", ResourceVersion:"",
    FieldPath:""}): type: 'Warning' reason: 'StorageClassCreateFailed' Failed to create StorageClass.storage.k8s.io/csi-manila-tripleo_ceph_nfs: StorageClass.storage.k8s.io "csi-manila-tripleo_
    ceph_nfs" is invalid: metadata.name: Invalid value: "csi-manila-tripleo_ceph_nfs": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must st
    art and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
    E1124 19:53:40.484042 1011457 base_controller.go:270] "ManilaController" controller failed to sync "key", err: StorageClass.storage.k8s.io "csi-manila-tripleo_ceph_nfs" is invalid: metadata
    .name: Invalid value: "csi-manila-tripleo_ceph_nfs": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumer
    ic character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
    I1124 19:53:40.484158 1011457 manila.go:87] Manila sync started
